name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: ant -noinput -buildfile build.xml dist
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist/lib
